eureka:
    instance:
        prefer-ip-address: true
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://registry:8761/eureka/
            
management:
    context-path: /management
    health:
        mail:
            enabled: false
