server:
    port: 6000

spring:
    redis:
      host: 127.0.0.1
      port: 6379

eureka:
    instance:
        prefer-ip-address: true
        appname: cacheservice
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
