server:
    port: 8081

spring:
    application:
        name: cacheservice
    cloud:
      config:
       uri: http://configserver:8888
       fail-fast: true

eureka:
    instance:
        prefer-ip-address: true
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/