server:
    port: 8761

spring:
    application:
        name: registry    
eureka:
    instance:
        hostname: localhost
        appname: registry
        prefer-ip-address: true
    server:
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/